import type { Monaco } from "@monaco-editor/react";

export const SEGFAULT_DARK_THEME = "segfault-dark";
export const SEGFAULT_LIGHT_THEME = "segfault-light";

const primary = "#D35959";

export function registerMonacoThemes(monaco: Monaco) {
  monaco.editor.defineTheme(SEGFAULT_DARK_THEME, {
    base: "vs-dark",
    inherit: true,
    rules: [
      { token: "comment", foreground: "78716c", fontStyle: "italic" },
      { token: "comment.doc", foreground: "78716c", fontStyle: "italic" },
      { token: "keyword", foreground: "D35959", fontStyle: "bold" },
      { token: "keyword.control", foreground: "D35959" },
      { token: "keyword.operator", foreground: "c04848" },
      { token: "keyword.other", foreground: "D35959" },
      { token: "storage", foreground: "D35959" },
      { token: "storage.type", foreground: "e8b4b4" },
      { token: "type", foreground: "e8b4b4" },
      { token: "type.identifier", foreground: "e8b4b4" },
      { token: "entity.name.type", foreground: "e8b4b4" },
      { token: "entity.name.function", foreground: "ededed" },
      { token: "support.function", foreground: "7aa2f7" },
      { token: "support.type", foreground: "e8b4b4" },
      { token: "variable", foreground: "d4d4d4" },
      { token: "variable.predefined", foreground: "e8b4b4" },
      { token: "variable.parameter", foreground: "d4d4d4" },
      { token: "constant", foreground: "f5c4c4" },
      { token: "constant.numeric", foreground: "f5c4c4" },
      { token: "constant.language", foreground: "D35959" },
      { token: "number", foreground: "f5c4c4" },
      { token: "number.hex", foreground: "f5c4c4" },
      { token: "number.float", foreground: "f5c4c4" },
      { token: "string", foreground: "7ec699" },
      { token: "string.escape", foreground: "e5c07b" },
      { token: "string.regexp", foreground: "e5c07b" },
      { token: "operator", foreground: "c04848" },
      { token: "delimiter", foreground: "a3a3a3" },
      { token: "delimiter.bracket", foreground: "d4d4d4" },
      { token: "tag", foreground: "D35959" },
      { token: "attribute.name", foreground: "e8b4b4" },
      { token: "attribute.value", foreground: "7ec699" },
      { token: "metatag", foreground: "78716c" },
      { token: "regexp", foreground: "e5c07b" },
      { token: "invalid", foreground: "ffffff", background: "D35959" },
    ],
    colors: {
      "editor.background": "#0a0a0a",
      "editor.foreground": "#ededed",
      "editorLineNumber.foreground": "#525252",
      "editorLineNumber.activeForeground": "#D35959",
      "editorCursor.foreground": primary,
      "editor.selectionBackground": "#D3595940",
      "editor.inactiveSelectionBackground": "#D3595926",
      "editor.lineHighlightBackground": "#D3595914",
      "editor.lineHighlightBorder": "#00000000",
      "editorGutter.background": "#0a0a0a",
      "editorWidget.background": "#171717",
      "editorWidget.border": "#262626",
      "editorSuggestWidget.background": "#171717",
      "editorSuggestWidget.border": "#262626",
      "editorSuggestWidget.selectedBackground": "#D3595933",
      "editorHoverWidget.background": "#171717",
      "editorHoverWidget.border": "#262626",
      "scrollbarSlider.background": "#D3595933",
      "scrollbarSlider.hoverBackground": "#D3595959",
      "scrollbarSlider.activeBackground": "#D3595980",
      "minimap.background": "#0a0a0a",
    },
  });

  monaco.editor.defineTheme(SEGFAULT_LIGHT_THEME, {
    base: "vs",
    inherit: true,
    rules: [
      { token: "comment", foreground: "78716c", fontStyle: "italic" },
      { token: "comment.doc", foreground: "78716c", fontStyle: "italic" },
      { token: "keyword", foreground: "c04848", fontStyle: "bold" },
      { token: "keyword.control", foreground: "c04848" },
      { token: "keyword.operator", foreground: "a33c3c" },
      { token: "keyword.other", foreground: "c04848" },
      { token: "storage", foreground: "c04848" },
      { token: "storage.type", foreground: "a33c3c" },
      { token: "type", foreground: "a33c3c" },
      { token: "type.identifier", foreground: "a33c3c" },
      { token: "entity.name.type", foreground: "a33c3c" },
      { token: "entity.name.function", foreground: "171717" },
      { token: "support.function", foreground: "4568a0" },
      { token: "support.type", foreground: "a33c3c" },
      { token: "variable", foreground: "262626" },
      { token: "variable.predefined", foreground: "a33c3c" },
      { token: "variable.parameter", foreground: "404040" },
      { token: "constant", foreground: "b34040" },
      { token: "constant.numeric", foreground: "b34040" },
      { token: "constant.language", foreground: "c04848" },
      { token: "number", foreground: "b34040" },
      { token: "number.hex", foreground: "b34040" },
      { token: "number.float", foreground: "b34040" },
      { token: "string", foreground: "2d6a4f" },
      { token: "string.escape", foreground: "92600f" },
      { token: "string.regexp", foreground: "92600f" },
      { token: "operator", foreground: "a33c3c" },
      { token: "delimiter", foreground: "525252" },
      { token: "delimiter.bracket", foreground: "404040" },
      { token: "tag", foreground: "c04848" },
      { token: "attribute.name", foreground: "a33c3c" },
      { token: "attribute.value", foreground: "2d6a4f" },
      { token: "metatag", foreground: "78716c" },
      { token: "regexp", foreground: "92600f" },
      { token: "invalid", foreground: "ffffff", background: "D35959" },
    ],
    colors: {
      "editor.background": "#ffffff",
      "editor.foreground": "#171717",
      "editorLineNumber.foreground": "#a3a3a3",
      "editorLineNumber.activeForeground": "#c04848",
      "editorCursor.foreground": primary,
      "editor.selectionBackground": "#D3595933",
      "editor.inactiveSelectionBackground": "#D359591a",
      "editor.lineHighlightBackground": "#fdf2f2",
      "editor.lineHighlightBorder": "#00000000",
      "editorGutter.background": "#fafafa",
      "editorWidget.background": "#ffffff",
      "editorWidget.border": "#e5e5e5",
      "editorSuggestWidget.background": "#ffffff",
      "editorSuggestWidget.border": "#e5e5e5",
      "editorSuggestWidget.selectedBackground": "#fbe8e8",
      "editorHoverWidget.background": "#ffffff",
      "editorHoverWidget.border": "#e5e5e5",
      "scrollbarSlider.background": "#D3595926",
      "scrollbarSlider.hoverBackground": "#D3595940",
      "scrollbarSlider.activeBackground": "#D3595959",
      "minimap.background": "#fafafa",
    },
  });
}

export function getSegfaultTheme(isDark: boolean) {
  return isDark ? SEGFAULT_DARK_THEME : SEGFAULT_LIGHT_THEME;
}
